/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_crakdemo2_MyJni */

#ifndef _Included_com_example_crakdemo2_MyJni
#define _Included_com_example_crakdemo2_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_crakdemo2_MyJni
 * Method:    isOk
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_crakdemo2_MyJni_isOk
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
